# -*- coding: utf-8 -*-
"""facerecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L-8fhW7xHYAog_3gqR0nYiU2OqaNrmip
"""

!pip install face_recognition

from google.colab import files

uploaded = files.upload()

from PIL import Image
import face_recognition

image = face_recognition.load_image_file("photo1.jpg")

face_locations = face_recognition.face_locations(image,number_of_times_to_upsample=0,model="cnn")
print('''I found{}face(s)in this photograph.'''.format(len(face_locations)))

face_locations

top,right,bottom,left=face_locations[0]
print("A face is located at pixel location")
face_image=image[top:bottom,left:right]
pill_image=Image.fromarray(face_image)
pill_image